# .github/workflows/ci.yml

name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Production:
    name: Deploy
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v3
      - name: Build & Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{secrets.SSH_HOST}}
          USER_NAME: ${{secrets.USER_NAME}}
          PATH: ${{secrets.PATH}}

        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key 
          echo private_key
