name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Production:
    name: Deploy
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          sudo chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key root@ssh.iliutaadrian.cloud '
          cd /DATA/Credit-Spread-Algo &&
          git reset --hard &&
          git checkout main &&
          git pull origin main &&
          docker compose down &&
          docker compose rm -fsv &&
          docker compose up --build -d
          '
