name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: connect to remote server
        uses: npgy/cloudflared-ssh-action@v2.0
        with:
          host: ${{ vars.HOST }}
          username: root
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22

      - name: Deploy
        commands: |
          cd /DATA/Credit-Spread-Algo
          touch test.txt

      # - name: Execute Deployment
      #   run: |
      #     ssh -o StrictHostKeyChecking=no -i private_key root@ssh.iliutaadrian.cloud '
      #       cd /DATA/Credit-Spread-Algo &&
      #       git reset --hard &&
      #       git checkout main &&
      #       git pull origin main &&
      #       docker-compose down &&
      #       docker-compose rm -fsv &&
      #       docker-compose up --build -d
      # '
